<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" encoding="UTF-8" indent="yes" />
  <xsl:template match="/rss">
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="omrss.gif" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="feed.css" />
        <title><xsl:value-of select="channel/title" /></title>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>
              <xsl:value-of select="channel/title" />
            </h1>
          </header>
          <main>
            <div class="content">
              <div class="menu-items">
                <xsl:for-each select="channel/item">
                  <div class="menu-item">
                    <h3>
                      <xsl:value-of select="title" />
                    </h3>
                    <div class="description">
                      <xsl:value-of
                        select="description"
                        disable-output-escaping="yes"
                      />
                    </div>
                  </div>
                </xsl:for-each>
              </div>
            </div>
          </main>
          <footer>
            <p>
              <strong>📰 This is an RSS feed.</strong> Subscribe by copying the
              URL into your RSS reader.
            </p>
            <p>
              Generated by <xsl:value-of select="channel/generator" /> |
              <a href="{channel/link}" target="_blank">Visit Website</a>
            </p>
            <p>Published: <xsl:value-of select="channel/pubDate" /></p>
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
