<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" encoding="UTF-8" indent="yes" />
  <xsl:template match="/rss">
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="omrss.gif" type="image/x-icon" />
        <link rel="stylesheet" href="https://schicho.github.io/shared/style.css"></link>
        <link rel="stylesheet" type="text/css" href="feed.css" />
        <title>
          <xsl:value-of select="channel/title" />
        </title>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>
              <xsl:value-of select="channel/title" />
            </h1>
          </header>
          <main>
            <div class="menu-items">
              <xsl:for-each select="channel/item">
                <div>
                  <h2>
                    <xsl:value-of select="title" />
                  </h2>
                  <p>
                    <xsl:value-of
                      select="description"
                      disable-output-escaping="yes"
                    />
                  </p>
                </div>
              </xsl:for-each>
            </div>
          </main>
          <footer>
            <p>Published <xsl:value-of select="channel/pubDate" />. Generated by <a
                href="https://schicho.github.io/openmensarss/">OpenMensa RSS</a>.</p>
            <p> This is an RSS feed. Subscribe by copying the URL into your RSS reader.</p>
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>