name: Generate OpenMensa RSS feeds

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-go@v5

      - name: Generate RSS xml files
        run: |
          go run cmd/generaterss/main.go

      - name: Commit and push to the repository
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add .
          # Force the build to succeed, even if no files were changed
          git commit -m 'Update RSS feeds' || true
          git push

  deploy:
    needs: generate-rss
    uses: ./.github/workflows/static.yml
